# Generated by Django 4.1.7 on 2023-02-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("video_id", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=2000)),
                ("duration", models.CharField(max_length=20)),
                ("iframe", models.CharField(max_length=2000)),
                ("image", models.URLField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
    ]
