# Generated by Django 4.1.7 on 2023-03-03 17:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("youtube_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sortby",
                    models.CharField(
                        choices=[
                            ("Relevance", "Relevance"),
                            ("Upload Date", "Upload Date"),
                        ],
                        default=None,
                        max_length=24,
                    ),
                ),
                (
                    "features",
                    models.CharField(
                        choices=[
                            ("Live", "Live"),
                            ("Subtitles/CC", "Subtitles/CC"),
                            ("HD", "HD"),
                        ],
                        default=None,
                        max_length=24,
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        choices=[
                            ("< 4min", "< 4min"),
                            ("4-20 min", "4-20 min"),
                            ("> 20min", "> 20min"),
                        ],
                        default=None,
                        max_length=24,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Video", "Video"),
                            ("Channel", "Channel"),
                            ("Playlist", "Playlist"),
                        ],
                        default=None,
                        max_length=24,
                    ),
                ),
                (
                    "upload_date",
                    models.CharField(
                        choices=[
                            ("Last Hour", "Last Hour"),
                            ("Today", "Today"),
                            ("This Week", "This Week"),
                            ("This Month", "This Month"),
                            ("This Year", "This Year"),
                        ],
                        default=None,
                        max_length=24,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("description", models.TextField(max_length=300)),
                ("path", models.CharField(max_length=60)),
                ("datetime", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="LikedListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("like_date", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="youtube_app.listing",
                    ),
                ),
            ],
        ),
    ]
