# Generated by Django 4.1.7 on 2023-03-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "youtube_app",
            "0003_filters_remove_likedlisting_listing_delete_link_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="filters",
            name="duration",
            field=models.CharField(
                choices=[
                    ("< 4min", "< 4min"),
                    ("4-20 min", "4-20 min"),
                    ("> 20min", "> 20min"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="filters",
            name="features",
            field=models.CharField(
                choices=[
                    ("Live", "Live"),
                    ("Subtitles/CC", "Subtitles/CC"),
                    ("HD", "HD"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="filters",
            name="sortby",
            field=models.CharField(
                choices=[("Relevance", "Relevance"), ("Upload Date", "Upload Date")],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="filters",
            name="type",
            field=models.CharField(
                choices=[
                    ("Video", "Video"),
                    ("Channel", "Channel"),
                    ("Playlist", "Playlist"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="filters",
            name="upload_date",
            field=models.CharField(
                choices=[
                    ("Last Hour", "Last Hour"),
                    ("Today", "Today"),
                    ("This Week", "This Week"),
                    ("This Month", "This Month"),
                    ("This Year", "This Year"),
                ],
                max_length=24,
            ),
        ),
    ]
